
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const LeadStatus = {
  novo: 'novo',
  conversa: 'conversa',
  proposta: 'proposta',
  ganho: 'ganho',
  perdido: 'perdido'
} as const

export type LeadStatus = (typeof LeadStatus)[keyof typeof LeadStatus]
